### PR TITLE
Only adding future holidays and removing past holidays + Support for Regional holidays

### PR DESCRIPTION
**Pull request by mitchelljb**
Adjustment in script to only add Future holidays. Also with Updating, it will remove holidays from the past + will update the schedule as default (before it was creating a new schedule).

### CODE REVIEW

**Comment by sjackson0109** [comment]
Another issue that you recognised and resolved without my help. Thank you!

Update needed:
- Can the comment on line 10 `-Not Append` be updated to `-NotAppend` ?  A simple space removal, to align the variable-name

Keep up the good work mate.

**Comment by sjackson0109** [comment]
@mitchelljb - looks like you have a branch file conflict. Can I leave you to resolve once you update your PR ?

**Comment by mitchelljb** [comment]
@sjackson0109 - Fixed 😉 Even added support for Regional holidays

**Comment by mitchelljb** [comment]
@sjackson0109 
Below fixes: 

- Fixed branch file conflict
- updated script to allow "-NotAppend" switch when updating
- Added regional holiday support with the switch "-Region". When not used, only Global (country accross) holidays will be added

**Comment by sjackson0109** [comment]
Outstanding work @mitchelljb

**Pull request merged**
